### ISSUE TITLE
How can I deploy a Vue-Cli Project with your ssr plugin to now?

### ISSUE THREAD

**Issue by GitGangGuy** [Akryum/vue-cli-plugin-ssr#135]
[Zeit Now](http://now.sh) is a great free webapp deployment tool and should even support Node servers by publishing them as lambda functions. Somehow, only when deploying with this plugin, it won't render anything (Client- and server-side-rendered output just consists of the curly bracket placeholders that should be replaced with scripts and styles etc.). [Screenshots can be found here](https://imgur.com/a/Ew8FoXI). What can I do about it? Is anyone into configuring now.sh for such tasks? Thanks a lot.

**Comment by franciscolourenco** [comment]
Also in interested to see an example of usage with firebase or google cloud function which run express.

**Comment by jvanst** [comment]
Thought I would post a comment here for those still looking for a potential solution. Cloud functions need a single node entry point.

1. Quick and dirty. A entry point that directly runs vue-cli-service instead of running the package script.
```
const Service = require('@vue/cli-service/lib/Service')
const service = new Service(process.cwd())

service.run(
  'ssr:serve', 
  { 'mode': 'production' },
  [ 'ssr:serve', '--mode', 'production' ]
)
```

Note: I had this in the root directory along side vue.config.js

2. Better Approach. Read through `@akryum/vue-cli-plugin-ssr/lib/app.js` and get an understanding of the underlying implementation. You can extend and even replace this.

**Comment by ghost** [comment]
I don't work with the Vue-Cli anymore, so I won't be able to elaborate on the hack above. I'll close this issue for now, if anyone else is still experiencing the same problem I'd be happy to reopen this.
