### ISSUE TITLE
SSR server forwarding cookies to apollo server?

### ISSUE THREAD

**Issue by beeplin** [Akryum/vue-cli-plugin-ssr#26]
This is a following issue from https://github.com/Akryum/vue-apollo/issues/400.

I am using `vue-cli-plugin-ssr` together with `vue-cli-plugin-apollo` and try to achieve proper SSR which prefetch data from the apollo server according to the authentication jwt from cookie.

My ssr server runs on `localhost:8000` and apollo server runs on `localhost:4000`.

After using cookie instead of http request headers to pass the jwt to the ssr server, I can see the cookie is successfully passed to the ssr server:

![image](https://user-images.githubusercontent.com/13058150/46083873-f3a98200-c1d4-11e8-9226-4af5635201e5.png)

But when the ssr server prefetches from the apollo server via its own http request, I can see it passes no cookie to it, therefore the prefetch is still no properly authenticated.

So now the problem is how to forward this cookie from the ssr server to the apollo server. The source code creating the ssr server here (https://github.com/Akryum/vue-cli-plugin-ssr/blob/master/lib/server.js#L4-L21) provides no interface to inject express middleware like `cookie-parser`, and I also couldn't find a way to export from here the express `req` object, which I believe is necessary in my `entry-server.js` file to customize the server-side `ApolloProvider`.

Any suggestions about that?

**Comment by zickat** [comment]
I sent a PR having the same problem #23 , it allow to add middlewares like cookieparser
Do you think it can revolve yours ?

**Comment by beeplin** [comment]
@zickat That's wonderful! And I just found a minute ago that the `context` parameter in `entry-server.js` just include `req.headers.cookie` which is the raw cookie string from the client. Before your PR I was afraid I had to parse the cookie string myself, and then here is your PR. :))

**Comment by zickat** [comment]
Thanks ! Hope it will be merged soon 👍

**Comment by Akryum** [comment]
When I have some spare time :smile_cat:

**Comment by jeissler** [comment]
@beeplin @zickat I'm having a similar issue trying to achieve proper ssr using `vue-cli-plugin-apollo` and `vue-cli-plugin-ssr`. Obviously it's using localstorage by default which I have overridden in `vue-apollo.js` `getAuth` option, so that is using cookies now... My confusion is how to then 'customize' apolloProvider inside `entry-server.js` to use the jwt from the cookie? I've found very little information outside of this ticket and the one other linked ticket about this although it seems it would be a common use case in ssr. Many thanks if someone can please elaborate a bit on how to achieve this.
